

nodejs-docs-samples:
	git clone https://github.com/GoogleCloudPlatform/nodejs-docs-samples

nodejs-install:  nodejs-docs-samples
	cd nodejs-docs-samples/appengine/hello-world/standard &&
	npm install &&
	npm start
