

run:
	yarn start
	#said so after launching this: npx create-react-app datamaps

install:
	npm install d3
	npm install datamaps
	npm install react-router
	yarn add d3
	yarn add datamaps
	yarn add react-router

update:
	npm install -g npm