
help:
	open https://wattenberger.com/blog/gauge
	cat Makefile

install:
	@echo La tizia mica te lo dice vabbe..
	npm install d3-shape
	npm install d3-scale
#	npm install react-router-dom

run:
	npm start

